### ISSUE TITLE
MQTT unstable and lacks basic features (12.0.1)

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1134]
in `12.0.1`, MQTT still is not stable :(
Also is misses some trivial features.

See https://github.com/jomjol/AI-on-the-edge-device/issues/1071 and other issues.

# Issues
- [x] init/connecting fails spordically
- [x]  random disconnects (might be due to identical `ClientID`s

# Improvements/Enhancements
- [x] Use unique default `ClientID` (https://github.com/jomjol/AI-on-the-edge-device/issues/1146)
- [x] refactor retries, simplify code
- [x] check why client start fails sometimes
- [x] improve logging
- [x] Add sysinfo topics (IP, MAC), see https://github.com/jomjol/AI-on-the-edge-device/issues/1195
- [x] Add Homeassistant Discovery (https://github.com/jomjol/AI-on-the-edge-device/issues/1133)

**Comment by vrjpellenz** [comment]
Thanks for re-opening the issue. MQTT is really important for me, since it fits nicely in my home automation environment. In about 20 % of the cases the MQTT transmission is successful, in the other cases I actually see two types of errors: 

...
2022-10-05T15:51:09: Branch: 'HEAD', Tag: 'v12.0.1', Revision: dfe2c46, Date/Time: 2022-09-29 17:13
...
2022-10-05T22:07:26: MQTT - Failed to publish 'gaszaehler/connection'!
2022-10-05T22:07:26: MQTT - Re-running init...!
2022-10-05T22:07:26: MQTT - Init
2022-10-05T22:07:26: MQTT - Init successful
2022-10-05T22:07:26: MQTT - Failed to publish 'gaszaehler/connection'!

and

2022-10-05T22:22:26: MQTT - Failed to publish 'gaszaehler/connection'!
2022-10-05T22:22:26: MQTT - Re-running init...!
2022-10-05T22:22:26: MQTT - Init
2022-10-05T22:22:31: MQTT - Could not start client!

**Comment by vrjpellenz** [comment]
@caco3 : I had a quick look at the code. Would it help to use a proven MQTT library (such as https://github.com/knolleary/pubsubclient) to make MQTT more stable? Is it too big?

**Comment by caco3** [comment]
I have not been involved on implementing it originally, I only had a look on it and tried to make it more reliable (but failed).

I would have expected that we already use a library, but might be wrong.

Anyway IMO we should use/try the official one from https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mqtt.html

@jomjol do you remember which one is in use?

**Comment by caco3** [comment]
btw, its also unstable for me, but most of the times it successfully re-inits and is able to publish.

**Comment by hilleke-dirk** [comment]
11.3.1 was unstable, 12.0.1 do not work at all (debian mqtt server)

always:
2022-10-09T00:09:41: MQTT - Failed to publish 'gaszaehler/connection'!
2022-10-09T00:09:41: MQTT - Re-running init...!
2022-10-09T00:09:41: MQTT - Init
2022-10-09T00:09:41: MQTT - Could not start client!

**Comment by hilleke-dirk** [comment]
I do not know why, but at the moment it works!????
I change several times the configuration and restarted.

**Comment by jomjol** [comment]
Then I suggest to close and observe. If it is a problem again, please open a new one.

**Comment by caco3** [comment]
I would like to keep it open until we cleanex out the whole MQTT stuff!
Its not stable for sure, I need re-inits all the time and the LWT fires all the time!

**Comment by caco3** [comment]
> @caco3 : I had a quick look at the code. Would it help to use a proven MQTT library (such as https://github.com/knolleary/pubsubclient) to make MQTT more stable? Is it too big?

I had a look, we use the latest official library form Espressif. Since they officially support this lib, I would not want to switch unless we can prove it is buggy. However since I can't find other bug reports showing stability issue with that lib, thats unlikely!

**Comment by caco3** [comment]
I just learned that it uses a hardcoded default client ID. So unless you don't set the `ClientID` in the MQTT settings, it always uses `watermeter`! Most likely mo disconnects where caused by this. I have to prove that next week and will improve the firmware to use a default ClientID based on its MAC address.

This does not explain why we cant start the client sometimes or why publishing fails, but it explains (my) random disconnects and maybe also the LWT firing.

**Comment by caco3** [comment]
There are some improvements coming with https://github.com/jomjol/AI-on-the-edge-device/pull/1232. We will see if this is enough.
Homeassistant Discovery will be added with https://github.com/jomjol/AI-on-the-edge-device/pull/1234
