### ISSUE TITLE
Release 15.1 Preparations

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#2157]
@jomjol @haverland @Slider0007 

Using `git log --show-pulls --oneline` in `rolling` I created following list.
As far as I can see, it contains all Pull requests since the last release (15.0.3) (its a bit tricky since there where some backports form master to rolling).

Can you please go through the list and:
1. Add a note about your pull request to the [changelog](https://github.com/jomjol/AI-on-the-edge-device/blob/release-15.1-preparations/Changelog.md) in https://github.com/jomjol/AI-on-the-edge-device/tree/release-15.1-preparations
2. Tick it off here so we see the progress?

Are there open bugs/features which we want to add to the 15.1 release?

### Pull Requests since v15.0
- [x] 431df73 Fix mqtt enable (#2144)
- [x] 1f5d4de Cleanup tflite (#2133)
- [x] ce00192 Print startblock after NTP snyc only once (#2129)
- [x] 28f3ad0 Update FeatureRequest.md (#2130)
- [x] f84f20b Set CPU frequency (#2125)
- [x] 2dfd55e move Wifi, LWIP and BSSI to PSRAm (#2117)
- [x] 806adcb Use PSRAM for MQTT publishing and make it scheduled (#2113)
- [x] 4dc4752 Add GJ (gigajoule) as an energy meter unit (#2114)
- [x] 8274230 added State Class "measurement" to rate_per_time_unit (#2116)
- [x] 6ca7897 "WIFI roaming" by channel scan (AP switching at low RSSI) (#2120)
- [x] 39b8b5b updated log message
- [x] 5b98aca ImageQuality: Set low input limit to 8 (#2108)
- [x] d3d241c Logfile: Print start indication block after time sync (#2106)
- [x] 8c7e86f Master (#2104)
- [x] a7dc377 The raw topic should have no unit and must be State Class "None", so it is handled as a string (#2103)
- [x] 2dd2d03 SD card basic R/W check + folder/file presence check (#2085)
- [x] 18e96d6 Update readconfigparam.js
- [x] a1a77ae Improve MQTT (#2091)
- [x] c5b20f3 new models ana-cont-11.0.5, ana-class100-1.5.7, dig-class100-1.6.0 (#2089)
- [x] add6cf5 catch empty values (#2096)
- [x] 493bd4d use a plotly version which only provides the basics, see https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-basic (#2095)
- [x] 53ff190 enhance data pages (#2088)
- [x] 9a9aa68 do not show value on recognition page (#2083)
- [x] a92cb69 Fix missing number list (#2082)
- [x] 90fa443 Migrate some UART logs to Logfile logs (#2079)
- [x] 7a9f61a Boot phase: Add more error handling + provide verbose output in error cases (#2020)
- [x] a8f8189 Keep the html folder on a flast structure (no subfolders). Else the OTA fails until >15.0.x because it does not create the needed subfolders (#2080)
- [x] 2c4bda9 Restructure webui menu (#2070)
- [x] 7b2a80a Enhance pages (#2075)

Added:
- [X] Support of Contrast & Saturation
- [X] Support of InfluxDB2

**Comment by jomjol** [comment]
I modified the changelog.md
